### ISSUE TITLE
As a devops I want dotenv for frontend to store backend base url so I can easily deploy

### ISSUE THREAD

**Issue by novellizator** [salsita/foosball-rating#66]
You can create a variable something like:
```
# when running on localhost
POST_HOST_BASE_URL=":3000/"

# when running in docker
POST_HOST_BASE_URL="/api" 

```
and use it in client-config.js
I call it post-host because of [1], maybe there's a better name possible

[1]https://uri.thephpleague.com/uri/4.0/components/overview/

**Comment by Fezzzi** [comment]
I would suggest creating two variables: `POST_URL_PORT` and `POST_URL_PATH_BASE` where respective one will be empty in each environment. This will bring more future flexibility and readability.

What do you think @novellizator ?
