### ISSUE TITLE
As a programmer I need to update dependencies

### ISSUE THREAD

**Issue by novellizator** [salsita/foosball-rating#68]
Even github tells us:

"We found potential security vulnerabilities in your dependencies.
You can see this message because you have been granted access to security alerts for this repository."

So running npm audit (fix) and checking if everything works like expected would be useful

**Comment by Fezzzi** [comment]
- `npm audit` on frontend required an update of `react-scripts`. Its bump to new version didn't result in any issues. 

 - `npm audit` on backend had a problem only with actual resolved  version of `lodash` in `package-lock.json`. Therefore there is nothing to be fixed there.

Am I forgetting something?

**Comment by Fezzzi** [comment]
Resolved in #93 and #94
